ChibiOS/HAL: QSPI Driver
QSPI Driver
HAL » Normal Drivers
Generic QSPI Driver.
Detailed Description
Generic QSPI Driver.
This module defines an abstract interface for a Quad SPI communication interface.
Precondition
In order to use the QSPI driver the HAL_USE_QSPI option must be enabled in halconf.h.
QSPI capabilities
#define QSPI_SUPPORTS_MEMMAP TRUE
DCR register options
#define STM32_DCR_CK_MODE (1U << 0U)
#define STM32_DCR_CSHT_MASK (7U << 8U)
#define STM32_DCR_CSHT(n) ((n) << 8U)
#define STM32_DCR_FSIZE_MASK (31U << 16U)
#define STM32_DCR_FSIZE(n) ((n) << 16U)
Configuration options
#define STM32_QSPI_USE_QUADSPI1 FALSE
QUADSPI1 driver enable switch.
#define STM32_QSPI_QUADSPI1_PRESCALER_VALUE 1
QUADSPI1 prescaler setting.
#define STM32_QSPI_QUADSPI1_IRQ_PRIORITY 10
QUADSPI1 interrupt priority level setting.
#define STM32_QSPI_QUADSPI1_DMA_PRIORITY 1
QUADSPI1 DMA priority (0..3|lowest..highest).
#define STM32_QSPI_QUADSPI1_DMA_IRQ_PRIORITY 10
QUADSPI1 DMA interrupt priority level setting.
#define STM32_QSPI_DMA_ERROR_HOOK(qspip) osalSysHalt("DMA failure")
QUADSPI DMA error hook.
#define STM32_USE_STM32_D1_WORKAROUND TRUE
Enables a workaround for a STM32L476 QUADSPI errata.
Transfer options
#define QSPI_CFG_CMD_MASK (0xFFLU << 0LU)
#define QSPI_CFG_CMD(n) ((n) << 0LU)
#define QSPI_CFG_CMD_MODE_MASK (3LU << 8LU)
#define QSPI_CFG_CMD_MODE_NONE (0LU << 8LU)
#define QSPI_CFG_CMD_MODE_ONE_LINE (1LU << 8LU)
#define QSPI_CFG_CMD_MODE_TWO_LINES (2LU << 8LU)
#define QSPI_CFG_CMD_MODE_FOUR_LINES (3LU << 8LU)
#define QSPI_CFG_ADDR_MODE_MASK (3LU << 10LU)
#define QSPI_CFG_ADDR_MODE_NONE (0LU << 10LU)
#define QSPI_CFG_ADDR_MODE_ONE_LINE (1LU << 10LU)
#define QSPI_CFG_ADDR_MODE_TWO_LINES (2LU << 10LU)
#define QSPI_CFG_ADDR_MODE_FOUR_LINES (3LU << 10LU)
#define QSPI_CFG_ADDR_SIZE_MASK (3LU << 12LU)
#define QSPI_CFG_ADDR_SIZE_8 (0LU << 12LU)
#define QSPI_CFG_ADDR_SIZE_16 (1LU << 12LU)
#define QSPI_CFG_ADDR_SIZE_24 (2LU << 12LU)
#define QSPI_CFG_ADDR_SIZE_32 (3LU << 12LU)
#define QSPI_CFG_ALT_MODE_MASK (3LU << 14LU)
#define QSPI_CFG_ALT_MODE_NONE (0LU << 14LU)
#define QSPI_CFG_ALT_MODE_ONE_LINE (1LU << 14LU)
#define QSPI_CFG_ALT_MODE_TWO_LINES (2LU << 14LU)
#define QSPI_CFG_ALT_MODE_FOUR_LINES (3LU << 14LU)
#define QSPI_CFG_ALT_SIZE_MASK (3LU << 16LU)
#define QSPI_CFG_ALT_SIZE_8 (0LU << 16LU)
#define QSPI_CFG_ALT_SIZE_16 (1LU << 16LU)
#define QSPI_CFG_ALT_SIZE_24 (2LU << 16LU)
#define QSPI_CFG_ALT_SIZE_32 (3LU << 16LU)
#define QSPI_CFG_DUMMY_CYCLES_MASK (0x1FLU << 18LU)
#define QSPI_CFG_DUMMY_CYCLES(n) ((n) << 18LU)
#define QSPI_CFG_DATA_MODE_MASK (3LU << 24LU)
#define QSPI_CFG_DATA_MODE_NONE (0LU << 24LU)
#define QSPI_CFG_DATA_MODE_ONE_LINE (1LU << 24LU)
#define QSPI_CFG_DATA_MODE_TWO_LINES (2LU << 24LU)
#define QSPI_CFG_DATA_MODE_FOUR_LINES (3LU << 24LU)
#define QSPI_CFG_SIOO (1LU << 28LU)
#define QSPI_CFG_DDRM (1LU << 31LU)
QSPI configuration options
#define QSPI_USE_WAIT TRUE
Enables synchronous APIs.
#define QSPI_USE_MUTUAL_EXCLUSION TRUE
Enables the qspiAcquireBus() and qspiReleaseBus() APIs.
Macro Functions
#define qspiStartCommandI(qspip, cmdp)
Sends a command without data phase.
#define qspiStartSendI(qspip, cmdp, n, txbuf)
Sends data over the QSPI bus.
#define qspiStartReceiveI(qspip, cmdp, n, rxbuf)
Receives data from the QSPI bus.
#define qspiMapFlashI(qspip, cmdp, addrp) qspi_lld_map_flash(qspip, cmdp, addrp)
Maps in memory space a QSPI flash device.
#define qspiUnmapFlashI(qspip) qspi_lld_unmap_flash(qspip)
Maps in memory space a QSPI flash device.
Low level driver helper macros
#define _qspi_wakeup_isr(qspip)
Wakes up the waiting thread.
#define _qspi_isr_code(qspip)
Common ISR code.
Typedefs
typedef struct QSPIDriver QSPIDriver
Type of a structure representing an QSPI driver.
typedef void(* qspicallback_t) (QSPIDriver *qspip)
Type of a QSPI notification callback.
Data Structures
struct QSPIConfig
Driver configuration structure.
struct QSPIDriver
Structure representing an QSPI driver.
struct qspi_command_t
Type of a QSPI command descriptor.
Functions
static void qspi_lld_serve_dma_interrupt (QSPIDriver *qspip, uint32_t flags)
Shared service routine.
static void qspi_lld_serve_interrupt (QSPIDriver *qspip)
Shared service routine.
OSAL_IRQ_HANDLER (STM32_QUADSPI1_HANDLER)
STM32_QUADSPI1_HANDLER interrupt handler.
void qspi_lld_init (void)
Low level QSPI driver initialization.
void qspi_lld_start (QSPIDriver *qspip)
Configures and activates the QSPI peripheral.
void qspi_lld_stop (QSPIDriver *qspip)
Deactivates the QSPI peripheral.
void qspi_lld_command (QSPIDriver *qspip, const qspi_command_t *cmdp)
Sends a command without data phase.
void qspi_lld_send (QSPIDriver *qspip, const qspi_command_t *cmdp, size_t n, const uint8_t *txbuf)
Sends a command with data over the QSPI bus.
void qspi_lld_receive (QSPIDriver *qspip, const qspi_command_t *cmdp, size_t n, uint8_t *rxbuf)
Sends a command then receives data over the QSPI bus.
void qspi_lld_map_flash (QSPIDriver *qspip, const qspi_command_t *cmdp, uint8_t **addrp)
Maps in memory space a QSPI flash device.
void qspi_lld_unmap_flash (QSPIDriver *qspip)
Unmaps from memory space a QSPI flash device.
void qspiInit (void)
QSPI Driver initialization.
void qspiObjectInit (QSPIDriver *qspip)
Initializes the standard part of a QSPIDriver structure.
void qspiStart (QSPIDriver *qspip, const QSPIConfig *config)
Configures and activates the QSPI peripheral.
void qspiStop (QSPIDriver *qspip)
Deactivates the QSPI peripheral.
void qspiStartCommand (QSPIDriver *qspip, const qspi_command_t *cmdp)
Sends a command without data phase.
void qspiStartSend (QSPIDriver *qspip, const qspi_command_t *cmdp, size_t n, const uint8_t *txbuf)
Sends a command with data over the QSPI bus.
void qspiStartReceive (QSPIDriver *qspip, const qspi_command_t *cmdp, size_t n, uint8_t *rxbuf)
Sends a command then receives data over the QSPI bus.
void qspiCommand (QSPIDriver *qspip, const qspi_command_t *cmdp)
Sends a command without data phase.
void qspiSend (QSPIDriver *qspip, const qspi_command_t *cmdp, size_t n, const uint8_t *txbuf)
Sends a command with data over the QSPI bus.
void qspiReceive (QSPIDriver *qspip, const qspi_command_t *cmdp, size_t n, uint8_t *rxbuf)
Sends a command then receives data over the QSPI bus.
void qspiMapFlash (QSPIDriver *qspip, const qspi_command_t *cmdp, uint8_t **addrp)
Maps in memory space a QSPI flash device.
void qspiUnmapFlash (QSPIDriver *qspip)
Unmaps from memory space a QSPI flash device.
void qspiAcquireBus (QSPIDriver *qspip)
Gains exclusive access to the QSPI bus.
void qspiReleaseBus (QSPIDriver *qspip)
Releases exclusive access to the QSPI bus.
Enumerations
enum qspistate_t {
QSPI_UNINIT = 0, QSPI_STOP = 1, QSPI_READY = 2, QSPI_ACTIVE = 3,
QSPI_COMPLETE = 4, QSPI_MEMMAP = 5
}
Driver state machine possible states.
Variables
QSPIDriver QSPID1
QUADSPI1 driver identifier.
Macro Definition Documentation
STM32_QSPI_USE_QUADSPI1
#define STM32_QSPI_USE_QUADSPI1 FALSE
QUADSPI1 driver enable switch.
If set to TRUE the support for QUADSPI1 is included.
Note
The default is FALSE.
Definition at line 66 of file hal_qspi_lld.h.
STM32_QSPI_QUADSPI1_PRESCALER_VALUE
#define STM32_QSPI_QUADSPI1_PRESCALER_VALUE 1
QUADSPI1 prescaler setting.
Note
This is the prescaler divider value 1..256. The maximum frequency varies depending on the STM32 model and operating conditions, find the details in the data sheet.
Definition at line 76 of file hal_qspi_lld.h.
Referenced by qspi_lld_start().
STM32_QSPI_QUADSPI1_IRQ_PRIORITY
#define STM32_QSPI_QUADSPI1_IRQ_PRIORITY 10
QUADSPI1 interrupt priority level setting.
Definition at line 83 of file hal_qspi_lld.h.
STM32_QSPI_QUADSPI1_DMA_PRIORITY
#define STM32_QSPI_QUADSPI1_DMA_PRIORITY 1
QUADSPI1 DMA priority (0..3|lowest..highest).
Definition at line 90 of file hal_qspi_lld.h.
STM32_QSPI_QUADSPI1_DMA_IRQ_PRIORITY
#define STM32_QSPI_QUADSPI1_DMA_IRQ_PRIORITY 10
QUADSPI1 DMA interrupt priority level setting.
Definition at line 97 of file hal_qspi_lld.h.
Referenced by qspi_lld_start().
STM32_QSPI_DMA_ERROR_HOOK
#define STM32_QSPI_DMA_ERROR_HOOK (qspip) osalSysHalt("DMA failure")
QUADSPI DMA error hook.
Definition at line 104 of file hal_qspi_lld.h.
STM32_USE_STM32_D1_WORKAROUND
#define STM32_USE_STM32_D1_WORKAROUND TRUE
Enables a workaround for a STM32L476 QUADSPI errata.
The document DM00111498 states: "QUADSPI_BK1_IO1 is always an input when the command is sent in dual or quad SPI mode". This workaround makes commands without address or data phases to be sent as alternate bytes.
Definition at line 115 of file hal_qspi_lld.h.
QSPI_USE_WAIT
#define QSPI_USE_WAIT TRUE
Enables synchronous APIs.
Note
Disabling this option saves both code and data space.
Definition at line 90 of file hal_qspi.h.
QSPI_USE_MUTUAL_EXCLUSION
#define QSPI_USE_MUTUAL_EXCLUSION TRUE
Enables the qspiAcquireBus() and qspiReleaseBus() APIs.
Note
Disabling this option saves both code and data space.
Definition at line 98 of file hal_qspi.h.
qspiStartCommandI
#define qspiStartCommandI (qspip, cmdp)
Value:
{                                    \
  osalDbgAssert(((cmdp)->cfg & QSPI_CFG_DATA_MODE_MASK) ==                  \
                QSPI_CFG_DATA_MODE_NONE,                                    \
                "data mode specified");                                     \
  (qspip)->state = QSPI_ACTIVE;                                             \
  qspi_lld_command(qspip, cmdp);                                            \
}
Sends a command without data phase.
Postcondition
At the end of the operation the configured callback is invoked.
Parameters
[in] qspip pointer to the QSPIDriver object
[in] cmdp pointer to the command descriptor
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 154 of file hal_qspi.h.
Referenced by qspiStartCommand().
qspiStartSendI
#define qspiStartSendI (qspip, cmdp, n, txbuf)
Value:
{                             \
  osalDbgAssert(((cmdp)->cfg & QSPI_CFG_DATA_MODE_MASK) !=                  \
                QSPI_CFG_DATA_MODE_NONE,                                    \
                "data mode required");                                      \
  (qspip)->state = QSPI_ACTIVE;                                             \
  qspi_lld_send(qspip, cmdp, n, txbuf);                                     \
}
Sends data over the QSPI bus.
This asynchronous function starts a transmit operation.
Postcondition
At the end of the operation the configured callback is invoked.
Parameters
[in] qspip pointer to the QSPIDriver object
[in] cmdp pointer to the command descriptor
[in] n number of bytes to send or zero if no data phase
[in] txbuf the pointer to the transmit buffer
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 174 of file hal_qspi.h.
Referenced by qspiStartSend().
qspiStartReceiveI
#define qspiStartReceiveI (qspip, cmdp, n, rxbuf)
Value:
{                          \
  osalDbgAssert(((cmdp)->cfg & QSPI_CFG_DATA_MODE_MASK) !=                  \
                QSPI_CFG_DATA_MODE_NONE,                                    \
                "data mode required");                                      \
  (qspip)->state = QSPI_ACTIVE;                                             \
  qspi_lld_receive(qspip, cmdp, n, rxbuf);                                  \
}
Receives data from the QSPI bus.
This asynchronous function starts a receive operation.
Postcondition
At the end of the operation the configured callback is invoked.
Parameters
[in] qspip pointer to the QSPIDriver object
[in] cmdp pointer to the command descriptor
[in] n number of bytes to receive or zero if no data phase
[out] rxbuf the pointer to the receive buffer
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 194 of file hal_qspi.h.
Referenced by qspiStartReceive().
qspiMapFlashI
#define qspiMapFlashI (qspip, cmdp, addrp) qspi_lld_map_flash(qspip, cmdp, addrp)
Maps in memory space a QSPI flash device.
Precondition
The memory flash device must be initialized appropriately before mapping it in memory space.
Parameters
[in] qspip pointer to the QSPIDriver object
[in] cmdp pointer to the command descriptor
[out] addrp pointer to the memory start address of the mapped flash or NULL
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 215 of file hal_qspi.h.
qspiUnmapFlashI
#define qspiUnmapFlashI (qspip) qspi_lld_unmap_flash(qspip)
Maps in memory space a QSPI flash device.
Postcondition
The memory flash device must be re-initialized for normal commands exchange.
Parameters
[in] qspip pointer to the QSPIDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 227 of file hal_qspi.h.
Referenced by qspiUnmapFlash().
_qspi_wakeup_isr
#define _qspi_wakeup_isr (qspip)
Value:
{                                           \
  osalSysLockFromISR();                                                     \
  osalThreadResumeI(&(qspip)->thread, MSG_OK);                              \
  osalSysUnlockFromISR();                                                   \
}
Wakes up the waiting thread.
Parameters
[in] qspip pointer to the QSPIDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 244 of file hal_qspi.h.
_qspi_isr_code
#define _qspi_isr_code (qspip)
Value:
{                                             \
  if ((qspip)->config->end_cb) {                                            \
    (qspip)->state = QSPI_COMPLETE;                                         \
    (qspip)->config->end_cb(qspip);                                         \
    if ((qspip)->state == QSPI_COMPLETE)                                    \
      (qspip)->state = QSPI_READY;                                          \
  }                                                                         \
  else                                                                      \
    (qspip)->state = QSPI_READY;                                            \
  _qspi_wakeup_isr(qspip);                                                  \
}
Common ISR code.
This code handles the portable part of the ISR code:
Callback invocation.
Waiting thread wakeup, if any.
Driver state transitions.
Note
This macro is meant to be used in the low level drivers implementation only.
Parameters
[in] qspip pointer to the QSPIDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 267 of file hal_qspi.h.
Referenced by qspi_lld_serve_interrupt().
Typedef Documentation
QSPIDriver
typedef struct QSPIDriver QSPIDriver
Type of a structure representing an QSPI driver.
Definition at line 177 of file hal_qspi_lld.h.
qspicallback_t
typedef void(* qspicallback_t) (QSPIDriver *qspip)
Type of a QSPI notification callback.
Parameters
[in] qspip pointer to the QSPIDriver object triggering the callback
Definition at line 185 of file hal_qspi_lld.h.
Enumeration Type Documentation
qspistate_t
enum qspistate_t
Driver state machine possible states.
Enumerator
QSPI_UNINIT
Not initialized.
QSPI_STOP
Stopped.
QSPI_READY
Ready.
QSPI_ACTIVE
Exchanging data.
QSPI_COMPLETE
Asynchronous operation complete.
QSPI_MEMMAP
In memory mapped mode.
Definition at line 113 of file hal_qspi.h.
Function Documentation
qspi_lld_serve_dma_interrupt()
static void qspi_lld_serve_dma_interrupt (QSPIDriver * qspip, uint32_t flags) static
Shared service routine.
Parameters
[in] qspip pointer to the QSPIDriver object
[in] flags pre-shifted content of the ISR register
Definition at line 60 of file hal_qspi_lld.c.
Referenced by qspi_lld_start().
qspi_lld_serve_interrupt()
static void qspi_lld_serve_interrupt (QSPIDriver * qspip) static
Shared service routine.
Parameters
[in] qspip pointer to the QSPIDriver object
Definition at line 78 of file hal_qspi_lld.c.
References _qspi_isr_code, QSPIDriver::dma, dmaStreamDisable, and dmaStreamGetTransactionSize.
OSAL_IRQ_HANDLER()
OSAL_IRQ_HANDLER (STM32_QUADSPI1_HANDLER)
STM32_QUADSPI1_HANDLER interrupt handler.
Function Class:
Interrupt handler, this function should not be directly invoked.
Definition at line 105 of file hal_qspi_lld.c.
qspi_lld_init()
void qspi_lld_init (void)
Low level QSPI driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 128 of file hal_qspi_lld.c.
References QSPIDriver::dma, QSPIDriver::dmamode, QSPIDriver::qspi, qspiObjectInit(), and STM32_DMA_STREAM.
Referenced by qspiInit().
qspi_lld_start()
void qspi_lld_start (QSPIDriver * qspip)
Configures and activates the QSPI peripheral.
Parameters
[in] qspip pointer to the QSPIDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 152 of file hal_qspi_lld.c.
References QSPIDriver::config, QSPIConfig::dcr, QSPIDriver::dma, dmaStreamAllocate(), dmaStreamSetPeripheral, QSPIDriver::qspi, qspi_lld_serve_dma_interrupt(), QSPI_STOP, rccEnableQUADSPI1, QSPIDriver::state, STM32_QSPI_QUADSPI1_DMA_IRQ_PRIORITY, and STM32_QSPI_QUADSPI1_PRESCALER_VALUE.
Referenced by qspiStart().
qspi_lld_stop()
void qspi_lld_stop (QSPIDriver * qspip)
Deactivates the QSPI peripheral.
Parameters
[in] qspip pointer to the QSPIDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 186 of file hal_qspi_lld.c.
References QSPIDriver::dma, dmaStreamRelease(), QSPIDriver::qspi, QSPI_READY, rccDisableQUADSPI1, and QSPIDriver::state.
Referenced by qspiStop().
qspi_lld_command()
void qspi_lld_command (QSPIDriver * qspip, const qspi_command_t * cmdp)
Sends a command without data phase.
Postcondition
At the end of the operation the configured callback is invoked.
Parameters
[in] qspip pointer to the QSPIDriver object
[in] cmd pointer to the command descriptor
Function Class:
Not an API, this function is for internal use only.
Definition at line 215 of file hal_qspi_lld.c.
qspi_lld_send()
void qspi_lld_send (QSPIDriver * qspip, const qspi_command_t * cmdp, size_t n, const uint8_t * txbuf)
Sends a command with data over the QSPI bus.
Postcondition
At the end of the operation the configured callback is invoked.
Parameters
[in] qspip pointer to the QSPIDriver object
[in] cmd pointer to the command descriptor
[in] n number of bytes to send
[in] txbuf the pointer to the transmit buffer
Function Class:
Not an API, this function is for internal use only.
Definition at line 252 of file hal_qspi_lld.c.
References QSPIDriver::dma, QSPIDriver::dmamode, dmaStreamSetMemory0, dmaStreamSetMode, and dmaStreamSetTransactionSize.
qspi_lld_receive()
void qspi_lld_receive (QSPIDriver * qspip, const qspi_command_t * cmdp, size_t n, uint8_t * rxbuf)
Sends a command then receives data over the QSPI bus.
Postcondition
At the end of the operation the configured callback is invoked.
Parameters
[in] qspip pointer to the QSPIDriver object
[in] cmd pointer to the command descriptor
[in] n number of bytes to send
[out] rxbuf the pointer to the receive buffer
Function Class:
Not an API, this function is for internal use only.
Definition at line 280 of file hal_qspi_lld.c.
References QSPIDriver::dma, QSPIDriver::dmamode, dmaStreamSetMemory0, dmaStreamSetMode, and dmaStreamSetTransactionSize.
qspi_lld_map_flash()
void qspi_lld_map_flash (QSPIDriver * qspip, const qspi_command_t * cmdp, uint8_t ** addrp)
Maps in memory space a QSPI flash device.
Precondition
The memory flash device must be initialized appropriately before mapping it in memory space.
Parameters
[in] qspip pointer to the QSPIDriver object
[in] cmdp pointer to the command descriptor
[out] addrp pointer to the memory start address of the mapped flash or NULL
Function Class:
Not an API, this function is for internal use only.
Definition at line 310 of file hal_qspi_lld.c.
References QSPIDriver::qspi.
qspi_lld_unmap_flash()
void qspi_lld_unmap_flash (QSPIDriver * qspip)
Unmaps from memory space a QSPI flash device.
Postcondition
The memory flash device must be re-initialized for normal commands exchange.
Parameters
[in] qspip pointer to the QSPIDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 338 of file hal_qspi_lld.c.
References QSPIDriver::qspi.
qspiInit()
void qspiInit (void)
QSPI Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 56 of file hal_qspi.c.
References qspi_lld_init().
Referenced by halInit().
qspiObjectInit()
void qspiObjectInit (QSPIDriver * qspip)
Initializes the standard part of a QSPIDriver structure.
Parameters
[out] qspip pointer to the QSPIDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 68 of file hal_qspi.c.
References QSPIDriver::config, QSPIDriver::mutex, QSPI_STOP, QSPIDriver::state, and QSPIDriver::thread.
Referenced by qspi_lld_init().
qspiStart()
void qspiStart (QSPIDriver * qspip, const QSPIConfig * config)
Configures and activates the QSPI peripheral.
Parameters
[in] qspip pointer to the QSPIDriver object
[in] config pointer to the QSPIConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 91 of file hal_qspi.c.
References QSPIDriver::config, qspi_lld_start(), QSPI_READY, QSPI_STOP, and QSPIDriver::state.
qspiStop()
void qspiStop (QSPIDriver * qspip)
Deactivates the QSPI peripheral.
Note
Deactivating the peripheral also enforces a release of the slave select line.
Parameters
[in] qspip pointer to the QSPIDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 116 of file hal_qspi.c.
References QSPIDriver::config, qspi_lld_stop(), QSPI_READY, QSPI_STOP, and QSPIDriver::state.
qspiStartCommand()
void qspiStartCommand (QSPIDriver * qspip, const qspi_command_t * cmdp)
Sends a command without data phase.
Postcondition
At the end of the operation the configured callback is invoked.
Parameters
[in] qspip pointer to the QSPIDriver object
[in] cmdp pointer to the command descriptor
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 141 of file hal_qspi.c.
References QSPI_READY, qspiStartCommandI, and QSPIDriver::state.
qspiStartSend()
void qspiStartSend (QSPIDriver * qspip, const qspi_command_t * cmdp, size_t n, const uint8_t * txbuf)
Sends a command with data over the QSPI bus.
Postcondition
At the end of the operation the configured callback is invoked.
Parameters
[in] qspip pointer to the QSPIDriver object
[in] cmdp pointer to the command descriptor
[in] n number of bytes to send
[in] txbuf the pointer to the transmit buffer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 165 of file hal_qspi.c.
References QSPI_READY, qspiStartSendI, and QSPIDriver::state.
qspiStartReceive()
void qspiStartReceive (QSPIDriver * qspip, const qspi_command_t * cmdp, size_t n, uint8_t * rxbuf)
Sends a command then receives data over the QSPI bus.
Postcondition
At the end of the operation the configured callback is invoked.
Parameters
[in] qspip pointer to the QSPIDriver object
[in] cmdp pointer to the command descriptor
[in] n number of bytes to send
[out] rxbuf the pointer to the receive buffer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 191 of file hal_qspi.c.
References QSPI_READY, qspiStartReceiveI, and QSPIDriver::state.
qspiCommand()
void qspiCommand (QSPIDriver * qspip, const qspi_command_t * cmdp)
Sends a command without data phase.
Precondition
In order to use this function the option QSPI_USE_WAIT must be enabled.
In order to use this function the driver must have been configured without callbacks (end_cb = NULL).
Parameters
[in] qspip pointer to the QSPIDriver object
[in] cmdp pointer to the command descriptor
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 219 of file hal_qspi.c.
qspiSend()
void qspiSend (QSPIDriver * qspip, const qspi_command_t * cmdp, size_t n, const uint8_t * txbuf)
Sends a command with data over the QSPI bus.
Precondition
In order to use this function the option QSPI_USE_WAIT must be enabled.
In order to use this function the driver must have been configured without callbacks (end_cb = NULL).
Parameters
[in] qspip pointer to the QSPIDriver object
[in] cmdp pointer to the command descriptor
[in] n number of bytes to send
[in] txbuf the pointer to the transmit buffer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 249 of file hal_qspi.c.
qspiReceive()
void qspiReceive (QSPIDriver * qspip, const qspi_command_t * cmdp, size_t n, uint8_t * rxbuf)
Sends a command then receives data over the QSPI bus.
Precondition
In order to use this function the option QSPI_USE_WAIT must be enabled.
In order to use this function the driver must have been configured without callbacks (end_cb = NULL).
Parameters
[in] qspip pointer to the QSPIDriver object
[in] cmdp pointer to the command descriptor
[in] n number of bytes to send
[out] rxbuf the pointer to the receive buffer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 281 of file hal_qspi.c.
qspiMapFlash()
void qspiMapFlash (QSPIDriver * qspip, const qspi_command_t * cmdp, uint8_t ** addrp)
Maps in memory space a QSPI flash device.
Precondition
The memory flash device must be initialized appropriately before mapping it in memory space.
Parameters
[in] qspip pointer to the QSPIDriver object
[in] cmdp pointer to the command descriptor
[out] addrp pointer to the memory start address of the mapped flash or NULL
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 313 of file hal_qspi.c.
qspiUnmapFlash()
void qspiUnmapFlash (QSPIDriver * qspip)
Unmaps from memory space a QSPI flash device.
Postcondition
The memory flash device must be re-initialized for normal commands exchange.
Parameters
[in] qspip pointer to the QSPIDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 339 of file hal_qspi.c.
References QSPI_MEMMAP, QSPI_READY, qspiUnmapFlashI, and QSPIDriver::state.
qspiAcquireBus()
void qspiAcquireBus (QSPIDriver * qspip)
Gains exclusive access to the QSPI bus.
This function tries to gain ownership to the QSPI bus, if the bus is already being used then the invoking thread is queued.
Precondition
In order to use this function the option QSPI_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] qspip pointer to the QSPIDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 366 of file hal_qspi.c.
References QSPIDriver::mutex.
qspiReleaseBus()
void qspiReleaseBus (QSPIDriver * qspip)
Releases exclusive access to the QSPI bus.
Precondition
In order to use this function the option QSPI_USE_MUTUAL_EXCLUSION must be enabled.
Parameters
[in] qspip pointer to the QSPIDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 382 of file hal_qspi.c.
References QSPIDriver::mutex.
Variable Documentation
QSPID1
QSPIDriver QSPID1
QUADSPI1 driver identifier.
Definition at line 43 of file hal_qspi_lld.c.